# Generated by Django 4.1.2 on 2023-02-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='totalproductcost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
