# Generated by Django 4.1.2 on 2023-03-01 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_cus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cus_address',
            name='phone',
            field=models.IntegerField(default=uuid.uuid1),
        ),
    ]
