# Generated by Django 4.1.2 on 2023-03-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_cus_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivarycharge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
