# Generated by Django 4.1.2 on 2023-03-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_order_delivarycharge_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cus_address',
            name='myorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='myorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.cus_address'),
        ),
    ]
