# Generated by Django 4.1.2 on 2023-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_cus_address_myorder_alter_order_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cus_address',
            name='landmark',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
