# Generated by Django 4.1.2 on 2023-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_cus_address_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cus_address',
            name='district',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
