# Generated by Django 4.1.3 on 2022-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='Product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
