# Generated by Django 4.1.3 on 2022-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_myproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='adddate',
            field=models.DateField(null=True, verbose_name='adddate'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='expirydate',
            field=models.DateField(null=True, verbose_name='expirydate'),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
