# Generated by Django 4.1.2 on 2023-02-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_myproduct_adddate_alter_myproduct_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
