# Generated by Django 4.1.2 on 2023-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_myproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
