# Generated by Django 4.1.2 on 2023-03-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_registration_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_image',
            field=models.ImageField(default=1, upload_to='user/'),
            preserve_default=False,
        ),
    ]
