# Generated by Django 4.1.2 on 2023-03-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_registration_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user_image',
            new_name='image',
        ),
    ]
