# Generated by Django 4.1.2 on 2023-03-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_registration_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='address',
            name='image',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='review',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registration'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.registration'),
        ),
    ]
