# Generated by Django 4.1.2 on 2023-03-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_address_dob_remove_address_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='panchayat',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
