# Generated by Django 4.1.2 on 2023-03-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_address_panchayat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=200, null=True)),
                ('catagory_image', models.ImageField(default='default.png', upload_to='catagory/')),
                ('discription', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='Aadhar',
            field=models.ImageField(default='default.png', upload_to='userimage/'),
        ),
        migrations.AddField(
            model_name='myproduct',
            name='catagory',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catagory'),
        ),
    ]
