# Generated by Django 4.1.2 on 2023-03-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_catagory_address_aadhar_myproduct_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproduct',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.myproduct'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
