# Generated by Django 4.1.2 on 2023-03-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_myproduct_adddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='idproof',
        ),
    ]
